FIND_PATH(UUID_INCLUDE_DIRS uuid/uuid.h)
FIND_LIBRARY(UUID_LIBRARIES NAMES uuid PATH)

IF(NOT UUID_LIBRARIES)
	SET(UUID_LIBRARIES "")
ENDIF(NOT UUID_LIBRARIES)

IF(UUID_INCLUDE_DIRS)
	SET(UUID_FOUND TRUE)
ENDIF(UUID_INCLUDE_DIRS)

IF(NOT UUID_FOUND)
	IF(UUID_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find UUID")
	ENDIF(UUID_FIND_REQUIRED)
ENDIF(NOT UUID_FOUND)